1.
Select nombre,AL# from alumno,matricula
where AL#_Matricula=Al#_Aumno
and Asig# = "BD3";
2.
SELECT ALUMNO.NOMBRE
FROM ALUMNO, MATRICULA, ASIGNATURA
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = ASIGNATURA.ASIG#
AND ASIGNATURA.NOMBRE = 'Bases de Datos';
3.
Select Pr#,Nombre_prof From Profesor,ASIGNATURA
where Asig#_Asignatura=Asig#_profesor
ANd Asig.nombre ="Programación 1";
4.
SELECT ASIGNATURA.NOMBRE, ASIGNATURA.CURSO
FROM ALUMNO, MATRICULA, ASIGNATURA
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = ASIGNATURA.ASIG#
AND ALUMNO.NOMBRE = 'José Pérez';
5.
SELECT DISTINCT PROFESOR.NOMBRE
FROM ALUMNO, MATRICULA, PROFESOR
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = PROFESOR.ASIG#
AND ALUMNO.NOMBRE = 'José Pérez';
6.
Select Distinct Alumno.Nombre
from Alumno,Matricula,Profesor
where Alumno.Al#=matricula.Al#
and profesor#Asig= matricula#Asig
and nombre_profesor="Juan Lopez";
7.
SELECT ALUMNO.NOMBRE
FROM ALUMNO, MATRICULA, ASIGNATURA
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = ASIGNATURA.ASIG#
AND ASIGNATURA.CURSO = 2
GROUP BY ALUMNO.AL#
HAVING COUNT(*) = (SELECT COUNT(*) FROM ASIGNATURA WHERE CURSO = 2);
8.
SELECT DISTINCT ALUMNO.NOMBRE
FROM ALUMNO, MATRICULA, ASIGNATURA
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = ASIGNATURA.ASIG#
AND ASIGNATURA.CURSO = 2;
9.
SELECT DISTINCT ALUMNO.NOMBRE
FROM ALUMNO, MATRICULA, ASIGNATURA
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = ASIGNATURA.ASIG#
AND ASIGNATURA.CURSO = 2 AND ALUMNO.CURSO != 2;
10.
SELECT NOMBRE
FROM ALUMNO
WHERE BECA = 'Sí' AND PROV != 'Granada';
11.
SELECT ALUMNO.NOMBRE
FROM ALUMNO, MATRICULA, ASIGNATURA
WHERE ALUMNO.AL# = MATRICULA.AL#
AND MATRICULA.ASIG# = ASIGNATURA.ASIG#
AND ALUMNO.EDAD > 25 AND ASIGNATURA.CURSO = 1;
12.
SELECT P1.NOMBRE AS Profesor1, P2.NOMBRE AS Profesor2, ASIGNATURA.NOMBRE AS Asignatura
FROM PROFESOR P1, PROFESOR P2, ASIGNATURA
WHERE P1.ASIG# = P2.ASIG# AND P1.PR# < P2.PR#
AND P1.ASIG# = ASIGNATURA.ASIG#;
13.
SELECT DISTINCT ASIGNATURA.NOMBRE
FROM ASIGNATURA, MATRICULA, ALUMNO
WHERE ASIGNATURA.ASIG# = MATRICULA.ASIG#
AND MATRICULA.AL# = ALUMNO.AL#
AND ALUMNO.PROV = 'Málaga';
14.
SELECT ALUMNO.NOMBRE
FROM ALUMNO
WHERE ALUMNO.AL# NOT IN (SELECT AL# FROM MATRICULA);



