CREATE TABLE ALUMNOS (
    DNI VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO1 VARCHAR(25) NOT NULL,
    APELLIDO2 VARCHAR(25) NOT NULL,
    DIRECCION VARCHAR(100),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'H')),
    FECHA_NACIMIENTO DATE,
    COD_CURSO INT NOT NULL,
    FOREIGN KEY (COD_CURSO) REFERENCES CURSOS(COD_CURSO)
);

CREATE TABLE CURSOS (
    COD_CURSO INT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(100) UNIQUE,
    DNI_PROFESOR VARCHAR(10),
    MAXIMO_ALUMNOS INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS INT NOT NULL,
    FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);

CREATE TABLE PROFESORES (
    DNI VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO1 VARCHAR(25) NOT NULL,
    APELLIDO2 VARCHAR(25) NOT NULL,
    DIRECCION VARCHAR(100),
    TITULO VARCHAR(100),
    GANA DECIMAL(10, 2) NOT NULL
);

INSERT INTO PROFESORES (DNI,
Nombre, 
Apellido1,
Apellido2,
Direccion,
TITULO,
GANA)
VALUES
('32432455',
'Juan',
'Arch',
'López',
'PuertaNegra,4',
'Ing.Informática',
7500 );

INSERT INTO PROFESORES (DNI,
Nombre, 
Apellido1,
Apellido2,
Direccion,
TITULO,
GANA)
VALUES
('43215643',
'María',
'Oliva',
'Rubio',
"JuanAlfonso32",
"Lda.Fil.Inglesa",
5400 );

INSERT INTO CURSOS ( COD_CURSO,
NOMBRE_CURSO , 
DNI_PROFESOR,
MAXIMO_ALUMNOS,
FECHA_INICIO,
FECHA_FIN,
NUM_HORAS)
VALUES
('1',
'InglésBásico',
'43215643',
'15',
"2000-11-01",
"2000-12-22",
"120" );

INSERT INTO CURSOS ( COD_CURSO,
NOMBRE_CURSO , 
DNI_PROFESOR,
MAXIMO_ALUMNOS,
FECHA_INICIO,
FECHA_FIN,
NUM_HORAS)
VALUES
('2',
'AdministraciónLinux',
'32432455',
null,
"2000-09-01",
null,
80 );

INSERT INTO ALUMNOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, DIRECCION, SEXO, FECHA_NACIMIENTO, COD_CURSO) VALUES
    ('Lucas', 'Manilva', 'Lopez', '123523', 'Alhamar3', 'H', '1979-11-01', '1'),
    ('Antonia', 'Lopez', 'Alcantara', '2567567', 'Maniqui21', 'M', NULL, '2'),
    ('Jose', 'Perez', 'Caballar', '4896765', 'Jarcha5', 'H', '1977-02-03', '1');
    --No puedo añadir a manuel ya que no puso su Sexo y lo tengo puesto para que solo tenga dos Opciones que son h y m ---

ALTER TABLE PROFESORES
ADD edad INT;

ALTER TABLE PROFESORES
ADD CONSTRAINT edad_valida CHECK (edad BETWEEN 18 AND 65);

ALTER TABLE CURSOS
ADD CONSTRAINT num_alumnos_min CHECK (MAXIMO_ALUMNOS >= 10);

ALTER TABLE CURSOS
ADD CONSTRAINT horas_curso_min CHECK (num_horas > 100);

